export { Sidebar } from './_common/sidebar';
export { QcIcoOutline } from './_common/qc_ico_outline';
export { SectionTitle } from './_common/section_title';
export { SliderNavigation } from './_common/slider_nav';
export { Hero } from './hero';
export { About } from './about';
export { Projects } from './projects';
export { Skills } from './skills';
export { Reviews } from './reviews';
